"""Reporting primitives.

Phase 1 ships the bare minimum the rest of the suite depends on:
- A report data model (``ReportData``) populated from the SQLite store
- Markdown renderer for the bug-bounty Part E1 / E2 structure
- HTML renderer (Jinja2) — used both for the dashboard preview and as the
  source for the Phase 7 PDF export

Richer formatters (PDF via WeasyPrint, XLSX via openpyxl) plug into the
same ``ReportData`` shape in later phases.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any

from .cvss import severity_for_score

# ──────────────────────────── Data shapes ────────────────────────────


@dataclass
class FindingSummary:
    id: int | None
    title: str
    severity: str
    cvss_score: float | None
    cvss_vector: str | None
    cwe: str | None
    affected_component: str | None
    description: str | None
    root_cause: str | None
    repro_steps: str | None
    impact: str | None
    remediation: str | None
    references: list[str] = field(default_factory=list)
    evidence_paths: list[str] = field(default_factory=list)


@dataclass
class ReportData:
    client: str
    primary_domain: str | None
    engagement_started: datetime | None
    engagement_ended: datetime | None
    scope_summary: str
    findings: list[FindingSummary] = field(default_factory=list)
    asset_count: int = 0

    def by_severity(self) -> dict[str, list[FindingSummary]]:
        buckets: dict[str, list[FindingSummary]] = {
            "Critical": [], "High": [], "Medium": [], "Low": [], "Informational": []
        }
        for f in self.findings:
            sev = (f.severity or "").capitalize()
            if sev == "Info":
                sev = "Informational"
            buckets.setdefault(sev, []).append(f)
        return buckets

    def severity_counts(self) -> dict[str, int]:
        return {sev: len(items) for sev, items in self.by_severity().items()}


# ──────────────────────────── Markdown renderer ────────────────────────────


def render_markdown(data: ReportData) -> str:
    """Render a report following the bug_bounty_procedure Part E1 structure."""
    lines: list[str] = []
    lines.append(f"# Vulnerability Assessment Report — {data.client}")
    if data.primary_domain:
        lines.append(f"\n**Primary domain:** {data.primary_domain}")
    started = data.engagement_started.date().isoformat() if data.engagement_started else "TBD"
    ended = data.engagement_ended.date().isoformat() if data.engagement_ended else "TBD"
    lines.append(f"**Engagement window:** {started} — {ended}")
    lines.append(f"**Assets discovered:** {data.asset_count}")
    lines.append("\n## Executive Summary\n")

    counts = data.severity_counts()
    summary = " ".join(
        f"{counts.get(s, 0)} {s.lower()}"
        for s in ("Critical", "High", "Medium", "Low", "Informational")
    )
    lines.append(
        f"Across {data.asset_count} assets in scope, we identified {summary}."
    )

    lines.append("\n## Risk Metrics\n")
    lines.append("| Severity | Count |")
    lines.append("|---|---|")
    for sev in ("Critical", "High", "Medium", "Low", "Informational"):
        lines.append(f"| {sev} | {counts.get(sev, 0)} |")

    lines.append("\n## Findings\n")
    for sev in ("Critical", "High", "Medium", "Low", "Informational"):
        bucket = data.by_severity().get(sev) or []
        if not bucket:
            continue
        lines.append(f"\n### {sev} ({len(bucket)})\n")
        for idx, f in enumerate(bucket, 1):
            lines.append(_render_finding_md(idx, f))

    lines.append("\n## Scope\n")
    lines.append(data.scope_summary or "_no scope summary recorded_")

    lines.append("\n## Appendix — Generation\n")
    lines.append(
        f"_Generated by Twisted at {datetime.now().isoformat(timespec='seconds')}._"
    )
    return "\n".join(lines)


def _render_finding_md(num: int, f: FindingSummary) -> str:
    parts: list[str] = []
    parts.append(f"#### {num}. {f.title}\n")
    score_bit = f"{f.cvss_score:.1f}" if f.cvss_score is not None else "N/A"
    parts.append(f"- **Severity:** {f.severity} (CVSS {score_bit})")
    if f.cvss_vector:
        parts.append(f"- **CVSS vector:** `{f.cvss_vector}`")
    if f.cwe:
        parts.append(f"- **CWE:** {f.cwe}")
    if f.affected_component:
        parts.append(f"- **Affected:** {f.affected_component}")
    if f.description:
        parts.append(f"\n**Description**\n\n{f.description}\n")
    if f.root_cause:
        parts.append(f"\n**Root cause**\n\n{f.root_cause}\n")
    if f.repro_steps:
        parts.append(f"\n**Steps to reproduce**\n\n{f.repro_steps}\n")
    if f.impact:
        parts.append(f"\n**Business impact**\n\n{f.impact}\n")
    if f.remediation:
        parts.append(f"\n**Remediation**\n\n{f.remediation}\n")
    if f.references:
        parts.append("\n**References**\n")
        for r in f.references:
            parts.append(f"- {r}")
    if f.evidence_paths:
        parts.append("\n**Evidence**\n")
        for p in f.evidence_paths:
            parts.append(f"- `{p}`")
    parts.append("")
    return "\n".join(parts)


# ──────────────────────────── HTML renderer ────────────────────────────

_HTML_TEMPLATE = """<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<title>{{ data.client }} — Vulnerability Assessment</title>
<style>
  body { font-family: -apple-system, system-ui, sans-serif; max-width: 980px;
         margin: 32px auto; padding: 0 24px; color: #1f2328; line-height: 1.5; }
  h1, h2, h3 { border-bottom: 1px solid #d0d7de; padding-bottom: 6px; }
  table { border-collapse: collapse; margin: 16px 0; }
  th, td { border: 1px solid #d0d7de; padding: 6px 10px; text-align: left; }
  .sev-Critical { color: #82071e; font-weight: 600; }
  .sev-High { color: #cf222e; font-weight: 600; }
  .sev-Medium { color: #9a6700; font-weight: 600; }
  .sev-Low, .sev-Informational { color: #57606a; }
  code, pre { background: #f6f8fa; padding: 2px 4px; border-radius: 4px; }
  .meta { color: #57606a; font-size: 0.9em; }
</style>
</head><body>
<h1>Vulnerability Assessment — {{ data.client }}</h1>
<p class="meta">
  Primary domain: <strong>{{ data.primary_domain or "n/a" }}</strong> &middot;
  Window: {{ started }} → {{ ended }} &middot;
  Assets in scope: {{ data.asset_count }}
</p>

<h2>Risk Metrics</h2>
<table><thead><tr><th>Severity</th><th>Count</th></tr></thead><tbody>
{% for sev in ("Critical", "High", "Medium", "Low", "Informational") -%}
<tr><td class="sev-{{ sev }}">{{ sev }}</td><td>{{ counts.get(sev, 0) }}</td></tr>
{% endfor -%}
</tbody></table>

{% for sev in ("Critical", "High", "Medium", "Low", "Informational") -%}
{% set bucket = by_severity.get(sev) or [] -%}
{% if bucket -%}
<h2 class="sev-{{ sev }}">{{ sev }} ({{ bucket|length }})</h2>
{% for f in bucket -%}
<h3>{{ loop.index }}. {{ f.title }}</h3>
<p class="meta">CVSS {{ ('%.1f' % f.cvss_score) if f.cvss_score is not none else 'n/a' }}
  {%- if f.cvss_vector %} &middot; <code>{{ f.cvss_vector }}</code>{% endif %}
  {%- if f.cwe %} &middot; {{ f.cwe }}{% endif %}</p>
{% if f.affected_component %}<p><strong>Affected:</strong> {{ f.affected_component }}</p>{% endif %}
{% if f.description %}<p>{{ f.description }}</p>{% endif %}
{% if f.repro_steps %}<h4>Steps to reproduce</h4><pre>{{ f.repro_steps }}</pre>{% endif %}
{% if f.remediation %}<h4>Remediation</h4><p>{{ f.remediation }}</p>{% endif %}
{% endfor -%}
{% endif -%}
{% endfor -%}

<h2>Scope</h2>
<pre>{{ data.scope_summary or "no scope summary recorded" }}</pre>

<p class="meta">Generated by Twisted at {{ now }}.</p>
</body></html>
"""


def render_html(data: ReportData) -> str:
    from jinja2 import Environment

    env = Environment(autoescape=True)
    tpl = env.from_string(_HTML_TEMPLATE)
    return tpl.render(
        data=data,
        counts=data.severity_counts(),
        by_severity=data.by_severity(),
        started=data.engagement_started.date().isoformat() if data.engagement_started else "TBD",
        ended=data.engagement_ended.date().isoformat() if data.engagement_ended else "TBD",
        now=datetime.now().isoformat(timespec="seconds"),
    )


# ──────────────────────────── Builder helpers ────────────────────────────


def finding_summary_from_orm(f: Any) -> FindingSummary:
    """Build a FindingSummary from a Finding ORM instance.

    Kept loose-typed so this module does not import from .models in a way that
    creates a circular dep with reporting being a primitive.
    """
    return FindingSummary(
        id=getattr(f, "id", None),
        title=f.title,
        severity=str(f.severity).split(".")[-1].lower() if f.severity else "info",
        cvss_score=f.cvss_score,
        cvss_vector=f.cvss_vector,
        cwe=f.cwe,
        affected_component=f.affected_component,
        description=f.description,
        root_cause=f.root_cause,
        repro_steps=f.repro_steps,
        impact=f.impact,
        remediation=f.remediation,
        references=list(f.references or []),
        evidence_paths=[e.redacted_path or e.path for e in (getattr(f, "evidence", []) or [])],
    )


def auto_severity(score: float | None) -> str:
    return severity_for_score(score) if score is not None else "Informational"
