"""Tests for reporting primitives."""

from __future__ import annotations

from datetime import UTC, datetime

import pytest

from twisted.core.reporting import (
    FindingSummary,
    ReportData,
    auto_severity,
    finding_summary_from_orm,
    render_html,
    render_markdown,
)


def _make_data() -> ReportData:
    return ReportData(
        client="ACME",
        primary_domain="acme.example",
        engagement_started=datetime(2026, 4, 1, tzinfo=UTC),
        engagement_ended=datetime(2026, 4, 25, tzinfo=UTC),
        scope_summary="exact: api.acme.example\nwildcard: acme.example",
        asset_count=42,
        findings=[
            FindingSummary(
                id=1, title="SQL Injection in /search", severity="High",
                cvss_score=8.6, cvss_vector="CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N",
                cwe="CWE-89", affected_component="https://acme.example/search?q=...",
                description="User input concatenated into query.",
                root_cause="No parameterised queries.",
                repro_steps="1. GET /search?q=' OR 1=1--",
                impact="Database extraction.",
                remediation="Switch to parameterised queries.",
                references=["https://owasp.org/www-community/attacks/SQL_Injection"],
                evidence_paths=["/mnt/c/.../shot1.png"],
            ),
            FindingSummary(
                id=2, title="Missing X-Frame-Options", severity="Low",
                cvss_score=3.1, cvss_vector=None, cwe="CWE-1021",
                affected_component="https://acme.example/",
                description=None, root_cause=None,
                repro_steps=None, impact=None,
                remediation="Add X-Frame-Options header.",
                references=[], evidence_paths=[],
            ),
        ],
    )


class TestAggregations:
    def test_by_severity_groups_correctly(self) -> None:
        data = _make_data()
        groups = data.by_severity()
        assert len(groups["High"]) == 1
        assert len(groups["Low"]) == 1
        assert len(groups["Critical"]) == 0

    def test_severity_counts(self) -> None:
        data = _make_data()
        counts = data.severity_counts()
        assert counts["High"] == 1
        assert counts["Low"] == 1
        assert counts["Critical"] == 0


class TestMarkdown:
    def test_markdown_contains_headings_and_findings(self) -> None:
        out = render_markdown(_make_data())
        assert "# Vulnerability Assessment Report — ACME" in out
        assert "## Risk Metrics" in out
        assert "### High (1)" in out
        assert "SQL Injection in /search" in out
        assert "CVSS 8.6" in out
        assert "Switch to parameterised queries" in out

    def test_markdown_omits_empty_severity_sections(self) -> None:
        out = render_markdown(_make_data())
        assert "### Critical (0)" not in out
        assert "### Critical" not in out  # heading only emitted when bucket non-empty


class TestHtml:
    def test_html_renders_and_escapes(self) -> None:
        out = render_html(_make_data())
        assert "<html" in out
        assert "ACME" in out
        # Jinja autoescape escapes the apostrophe in repro steps
        assert "&#39;" in out or "OR 1=1" in out
        # severity classes present
        assert 'class="sev-High"' in out
        assert "Generated by Twisted" in out


class TestFromOrm:
    def test_from_orm_with_minimal_attrs(self) -> None:
        class FakeFinding:
            id = 7
            title = "x"
            severity = "FindingSeverity.MEDIUM"
            cvss_score = 5.0
            cvss_vector = None
            cwe = None
            affected_component = None
            description = None
            root_cause = None
            repro_steps = None
            impact = None
            remediation = None
            references = None
            evidence = []

        s = finding_summary_from_orm(FakeFinding())
        assert s.severity == "medium"
        assert s.title == "x"
        assert s.cvss_score == 5.0


class TestAutoSeverity:
    @pytest.mark.parametrize(
        ("score", "expected"),
        [(None, "Informational"), (0.0, "None"), (3.5, "Low"), (5.5, "Medium"),
         (8.0, "High"), (9.5, "Critical")],
    )
    def test_buckets(self, score: float | None, expected: str) -> None:
        assert auto_severity(score) == expected
